### ISSUE TITLE
Usage clarification requested (proper socket recv in interaction with the lib)

### ISSUE THREAD

**Issue by jite** [nodejs/http-parser#339]
From a webserver perspective (C, Linux, TCP sockets), I want to know exactly how many bytes to read from the socket for the header + the body.

Starting with accepting an incoming connection and now I want to 1) read from the socket, and then 2) parse the data.

According to specs:
1 Read data from socket until \r\n\r\n is hit, that's our HTTP header.
2 If it's (for instance) a POST req with Content-Length set, read Content-Length bytes of body payload

Doing nr 1 is easy, however after this stage I need to access the Content-Length value to know how many more bytes to read. Is it meant that I have to manually keep track of this and save it (in on_header_field/on_header_value callbacks)? According to the header file the parser->content_length is internal and can't be used.

Second thing, am I supposed to pause the parser here, read Content-Length bytes of data from the socket and then unpause the parser? That can't be right either since the length argument I sent to http_parser_execute() was set before I even had parsed Content-Length. Do I call http_parser_execute() again but just on the body/data payload with body/data len after this? (+ adding a check for http_body_is_final() to make sure there's not more data to read? If not final read more data and call http_parser_execute again?)

The docs could really be improved here or some useful example provided.

Just doing recv(sock, &buf, **some_big_buflen**, 0); doesn't cut it due to TCP.

**EDIT:** I just realized, as always when actually writing things down: Perhaps that's just the thing, recv(..some_big_buflen..) **does** cut it as it's up to the parser to keep track of state and me to follow the states and do actions accordingly.

**Comment by ploxiln** [comment]
Reading from a TCP connection into a big buffer is indeed the right way to do it. You will have your `on_body` callback called with chunks of the body, and you will know you've gotten them all due to the `on_message_complete` callback. You can receive and process just part of a request, or multiple at once, and all the callbacks will occur in sequence appropriately. 

The documentation assumes you are familiar with the idea, or figure out the tcp-stream-chunk nature of this ... it says "One http_parser object is used per TCP connection", and later "The parser maintains state and never looks behind, so buffering the data is not necessary", and the first example reads into an 80 KiB buffer. It could be clearer up-front, I guess ...

**Comment by jite** [comment]
Yeah as my edit suggests, I kinda figured like a minute after I wrote the original post.
As a(n embedded) developer I know how obvious things get when they've become obvious, so making "good" documentation is IMO one of the hardest things to do (especially going back to imagining what the non-obvious things even were).

I think the part about how central the parser actually is (regarding state and input) could be made a bit clearer though. I'll close this as I figured it out. Thanks for confirming.
