### ISSUE TITLE
should the 'enum state' move to http-parser.h ?

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/http-parser#402]
In practical application, any event fired, but the processing flow does not completed in fact. So, we have to check the state like below ... 
But the '**enum state**' is in the _http-parser.c_ file. We have to move it to _http-parser.h_ manually.
![image](https://user-images.githubusercontent.com/5990337/34342085-8af833d6-e9e0-11e7-8deb-c773dcbf9cc0.png)

**Comment by bnoordhuis** [comment]
Your point is not entirely clear to me but I can answer your question: no, `state` can't be promoted to public API because it is not stable - enumerations come and go as necessary.

You don't need it either because you can track yourself what state you are in inside the callback: start of header field, continuation of that field, start of header value, etc.  See the parser in node.js for an example: https://github.com/nodejs/node/blob/094d92bb57207fbc184bf15ef83591416333f1cf/src/node_http_parser.cc#L205-L240
